import type { CustomerFormValues } from "@/components/subscriptions/edit-customer-information-modal";

/** Demo customer row: identity + default address/phone for Edit customer. */
export type CustomerDemoProfile = {
  id: string;
  name: string;
  email: string;
  avatarBg?: string;
} & Omit<CustomerFormValues, "name" | "email">;

/**
 * Mock directory — each row has a distinct country, region, postal format, dial code, and number.
 * Country names match `iso-countries.json` / `normalizeCountryName`.
 */
export const CUSTOMER_DEMO_PROFILES: CustomerDemoProfile[] = [
  {
    id: "sg",
    name: "Sarthak Goyal",
    email: "hey@uixchef.com",
    avatarBg: "#f2f4f7",
    phone: "+918690001213",
    address: "2/112, Friends Colony, Raja Park",
    country: "India",
    state: "Rajasthan",
    city: "Jaipur",
    zip: "302031",
  },
  {
    id: "eb",
    name: "Erin Ekstrom Bothman",
    email: "erinekstrombothman@gmail.com",
    avatarBg: "#dbeafe",
    phone: "+13105550101",
    address: "1842 Sunset Plaza Dr",
    country: "United States of America",
    state: "California",
    city: "Los Angeles",
    zip: "90028",
  },
  {
    id: "mc",
    name: "Madelyn Calzoni",
    email: "madelyncalzoni@gmail.com",
    avatarBg: "#dbc0dd",
    phone: "+442071234501",
    address: "14 Baker Street",
    country: "United Kingdom of Great Britain and Northern Ireland",
    state: "England",
    city: "London",
    zip: "NW1 6XE",
  },
  {
    id: "mg",
    name: "Madelyn Geidt",
    email: "madelyngeidt@gmail.com",
    avatarBg: "#d1baa9",
    phone: "+14165550102",
    address: "220 King St W Suite 500",
    country: "Canada",
    state: "Ontario",
    city: "Toronto",
    zip: "M5H1K4",
  },
  {
    id: "ds",
    name: "Dulce Schleifer",
    email: "dulceschleifer@gmail.com",
    avatarBg: "#dfcc9f",
    phone: "+612987654321",
    address: "88 George Street",
    country: "Australia",
    state: "New South Wales",
    city: "Sydney",
    zip: "2000",
  },
  {
    id: "am",
    name: "Allison Mango",
    email: "allisonmango@gmail.com",
    avatarBg: "#c2c7b8",
    phone: "+498912345601",
    address: "Marienplatz 8",
    country: "Germany",
    state: "Bavaria",
    city: "Munich",
    zip: "80331",
  },
  {
    id: "oj",
    name: "Olivia John",
    email: "olivia.john@gmail.com",
    avatarBg: "#f2f4f7",
    phone: "+33142688601",
    address: "18 Rue de Rivoli",
    country: "France",
    state: "Île-de-France",
    city: "Paris",
    zip: "75001",
  },
  {
    id: "jh",
    name: "James Hall",
    email: "james.hall@gmail.com",
    avatarBg: "#dfcc9f",
    phone: "+5511987654321",
    address: "Av. Paulista 1578",
    country: "Brazil",
    state: "São Paulo",
    city: "São Paulo",
    zip: "01310-100",
  },
  {
    id: "ku",
    name: "Kris Ullman",
    email: "kris.ullman@gmail.com",
    avatarBg: "#c2c7b8",
    phone: "+523312345678",
    address: "Av. Chapultepec 480",
    country: "Mexico",
    state: "Jalisco",
    city: "Guadalajara",
    zip: "44100",
  },
  {
    id: "lb",
    name: "Lori Bryson",
    email: "lori.bryson@gmail.com",
    avatarBg: "#d1baa9",
    phone: "+81312345601",
    address: "2 Chome-8 Shibuya",
    country: "Japan",
    state: "Tokyo",
    city: "Shibuya",
    zip: "1500002",
  },
  {
    id: "cg",
    name: "Chris Glasser",
    email: "chris.glasser@gmail.com",
    avatarBg: "#f2f4f7",
    phone: "+6591234567",
    address: "1 Raffles Place",
    country: "Singapore",
    state: "Central Singapore",
    city: "Singapore",
    zip: "048616",
  },
  {
    id: "mw",
    name: "Marcus Webb",
    email: "marcus.webb@gmail.com",
    avatarBg: "#dbeafe",
    phone: "+971501234567",
    address: "Sheikh Zayed Rd, Tower A",
    country: "United Arab Emirates",
    state: "Dubai",
    city: "Dubai",
    zip: "00000",
  },
  {
    id: "ps",
    name: "Priya Sharma",
    email: "priya.sharma@gmail.com",
    avatarBg: "#dbc0dd",
    phone: "+8613812345678",
    address: "Chaoyang Park South Rd 8",
    country: "China",
    state: "Beijing",
    city: "Beijing",
    zip: "100026",
  },
  {
    id: "nc",
    name: "Noah Chen",
    email: "noah.chen@gmail.com",
    avatarBg: "#dfcc9f",
    phone: "+821012345678",
    address: "Gangnam-daero 123",
    country: "Korea, Republic of",
    state: "Seoul-teukbyeolsi",
    city: "Seoul",
    zip: "03151",
  },
  {
    id: "tr",
    name: "Taylor Reid",
    email: "taylor.reid@gmail.com",
    avatarBg: "#c2c7b8",
    phone: "+46701234567",
    address: "Drottninggatan 71",
    country: "Sweden",
    state: "Stockholm",
    city: "Stockholm",
    zip: "11122",
  },
  {
    id: "av",
    name: "Avery Kim",
    email: "avery.kim@gmail.com",
    avatarBg: "#f2f4f7",
    phone: "+6491234567",
    address: "88 Queen Street",
    country: "New Zealand",
    state: "Auckland",
    city: "Auckland",
    zip: "1010",
  },
  {
    id: "jr",
    name: "Jordan Rivera",
    email: "jordan.rivera@gmail.com",
    avatarBg: "#dbeafe",
    phone: "+34912345678",
    address: "Calle Gran Vía 31",
    country: "Spain",
    state: "Madrid",
    city: "Madrid",
    zip: "28013",
  },
  {
    id: "em",
    name: "Emma Fitzgerald",
    email: "emma.fitzgerald@gmail.com",
    avatarBg: "#dbc0dd",
    phone: "+31201234567",
    address: "Keizersgracht 123",
    country: "Netherlands, Kingdom of the",
    state: "Noord-Holland",
    city: "Amsterdam",
    zip: "1015 CJ",
  },
];
